export const userAction = {
  LOGIN_PENDING: "LOGIN_PENDING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_RESET: "LOGIN_RESET",

  GET_INFO_PENDING: "GET_INFO_PENDING",
  GET_INFO_SUCCESS: "GET_INFO_SUCCESS",
  GET_INFO_FAILURE: "GET_INFO_FAILURE",

  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",

  LOGOUT_PENDING: "LOGOUT_PENDING",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  LOGOUT_RESET: "LOGOUT_RESET"
};

export const postAction = {
  GET_POST_PENDING: "GET_POST_PENDING",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAILURE: "GET_POST_FAILURE",
  GET_POST_RESET: "GET_POST_RESET",

  GET_POST_INFO_PENDING: "GET_POST_INFO_PENDING",
  GET_POST_INFO_SUCCESS: "GET_POST_INFO_SUCCESS",
  GET_POST_INFO_FAILURE: "GET_POST_INFO_FAILURE",
  GET_POST_INFO_RESET: "GET_POST_INFO_RESET",

  CREATE_POST_PENDING: "CREATE_POST_PENDING",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",
  CREATE_POST_RESET: "CREATE_POST_RESET"
};
